phase02 full-text-search
SeyedMojtaba1/codestar-software-engineering pull request #1
Opened 2024-09-06 15:37 UTC by SeyedMojtaba1

2024-09-08 18:12 UTC, navidnasyry commented on InvertedIndex/EnglishData/57110
اینا چیه؟؟؟؟؟؟؟؟؟
فایل های داده باید بیاد رو گیتهاب؟؟؟؟؟؟

2024-09-08 18:12 UTC, navidnasyry commented on InvertedIndex/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
say hello to .gitignore...:)))

2024-09-08 18:12 UTC, navidnasyry commented on InvertedIndex/obj/Debug/net8.0/ref/InvertedIndex.dll
dll....github???

2024-09-08 18:19 UTC, navidnasyry reviewed
یه گیت ایگنور درست حسابی بدون هیچی فایل اضافه روی گیت
منطقا قطعا حتما چند فایلی باید کد زده بشه دیگه...:(

2024-09-08 18:19 UTC, navidnasyry commented on InvertedIndex/Program.cs
> +﻿using System;
همش یه فایل؟؟؟
هر کلاس و اینترفیس تو فایل‌های متفاوت با پوشه بندی مناسب

2024-09-08 18:19 UTC, navidnasyry commented on InvertedIndex/Program.cs
> +        public Dictionary<int, List<string>> ExtarcAllFiles(string path)
typo

2024-09-08 18:19 UTC, navidnasyry commented on InvertedIndex/Program.cs
> +            for(int i = 0 ; i < allFiles.Length ; i++)
foreach

2024-09-12 11:34 UTC, navidnasyry requested changes
هر کلاس باید توی یه فایل باشه. یعنی فایلی نباشه که بیش از یک کلاس داشته باشه.:)

2024-09-12 11:34 UTC, navidnasyry commented on .vscode/settings.json
این فایل باید رو گیت باشه؟

2024-09-12 11:34 UTC, navidnasyry commented on InvertedIndex/bin/Debug/net8.0/InvertedIndex.deps.json
say hello to .gitignore:)

2024-09-12 11:34 UTC, navidnasyry commented on InvertedIndex/obj/Debug/net8.0/InvertedIndex.AssemblyInfo.cs
فایل‌های obj و  bin رو نمیذاریم رو گیت. چرا؟

2024-09-12 11:34 UTC, navidnasyry commented on InvertedIndex/obj/InvertedIndex.csproj.nuget.dgspec.json
فایل های dll رو میذاریم رو گیت؟

2024-09-12 11:36 UTC, navidnasyry commented on InvertedIndex/Program.cs
> +            }
S => SOLID

2024-09-12 11:36 UTC, navidnasyry commented on InvertedIndex/Program.cs
> +        }
S

2024-09-12 11:37 UTC, navidnasyry commented on InvertedIndex/Program.cs
> +            string txtDirPath = "./EnglishData";
read from ENV

2024-09-12 11:44 UTC, SeyedMojtaba1 commented on InvertedIndex/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs
Ok.🥲

2024-09-12 11:44 UTC, SeyedMojtaba1 commented on InvertedIndex/EnglishData/57110
قاعدتا نه اما نمیدونستم چه فایل هایی باید باشه چه فایل هایی نباید.

2024-09-12 11:51 UTC, SeyedMojtaba1 commented on InvertedIndex/obj/Debug/net8.0/ref/InvertedIndex.dll
👍

2024-09-12 12:34 UTC, SeyedMojtaba1 commented on InvertedIndex/Program.cs
> +﻿using System;
انجام شد.

2024-09-12 12:41 UTC, SeyedMojtaba1 commented on InvertedIndex/Program.cs
> +            for(int i = 0 ; i < allFiles.Length ; i++)
Ok. I fixed it.

2024-09-12 12:47 UTC, SeyedMojtaba1 commented on .vscode/settings.json
برداشتمش.

2024-09-12 12:47 UTC, SeyedMojtaba1 commented on InvertedIndex/bin/Debug/net8.0/InvertedIndex.deps.json
Ok🥲😂

2024-09-12 12:54 UTC, SeyedMojtaba1 commented on InvertedIndex/obj/Debug/net8.0/InvertedIndex.AssemblyInfo.cs
چون هم حجم زیادی دارن و در طول فرایند بیلد ساخته میشن و مخصوص سیستم خودمونه.

2024-09-12 12:59 UTC, SeyedMojtaba1 commented on InvertedIndex/obj/InvertedIndex.csproj.nuget.dgspec.json
نه نمیذاریم.

2024-09-13 06:07 UTC, SeyedMojtaba1 commented on InvertedIndex/Program.cs
> +        }
این کلاس فقط یه وظیفه داره که آرگومان ها رو طبقه بندی کنه.

2024-09-13 06:09 UTC, SeyedMojtaba1 commented on InvertedIndex/Program.cs
> +            }
این موارد پشت هم هستن و برای همین از هم جدا نشدن.

2024-09-13 06:40 UTC, SeyedMojtaba1 commented on InvertedIndex/Program.cs
> +            string txtDirPath = "./EnglishData";
Ok. But I think I did it wrong.

2024-09-13 06:41 UTC, SeyedMojtaba1 commented on InvertedIndex/Program.cs
> +            string txtDirPath = "./EnglishData";
Actually it is not optimized.

2024-09-13 17:44 UTC, navidnasyry requested changes
نکته بسیاااااااااااار مهم:
کلاس ها نباید به پیاده سازی های همدیگه وابسته باشن ...و فقط باید به interface ها وابسته باشن 
(طبق اصول سالید...کدوم اصل؟)
پس همه کلاس ها باید یه اینترفیس داشته باشه قطعا که هرجایی نیاز شد از اون کلاس استفاده بشه، از اینترفیس هاش استفاده بشه.

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/Program.cs
> +            ExecuteSearch exse = new ExecuteSearch();
نام متغیر واضح تر و کامل تر

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/Program.cs
> +            }
فقط داره بجز عضو اول کپی میگیره؟ راه بهتر...

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/Program.cs
> +            }
و البته خوانا تر
و اگه داره یه کار خاصی رو انجام میده میتونه یه کلاس بشه

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/Program.cs
> +            ReadtxtFile rtf = new ReadtxtFile();
متغیر ها واضح تر نام گذاری بشه

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/Program.cs
> +            ReadtxtFile rtf = new ReadtxtFile();
نوع متغیر ها در تعریف ها بهتره از var استفاده بشه...
چرا؟

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/DataLoading/ReadFiles.cs
> +        public Dictionary<int, List<string>> ExtarcAllFiles(string path)
typo
غلط املایی

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/DataLoading/ReadFiles.cs
> +            Dictionary<int, List<string>> doc = new Dictionary<int, List<string>>();
var

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/DataLoading/ReadFiles.cs
> +    class ReadtxtFile
اسم  کلاس با اسم فایل یکی باشه

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/Program.cs
> +            doc = rtf.ExtarcAllFiles(args[0]);
خوبه که از پارامتر های برنامه میخونه آدرس رو
ولی بهتره از ENV بخونه.

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/DataLoading/DictionaryFromDocs.cs
> +    class MakeDictionary
هم نام با فایل

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/DataLoading/ReadFiles.cs
> +                MakeDictionary md = new MakeDictionary();
NAMING... md?!:)

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/DataLoading/ReadFiles.cs
> +    class ReadtxtFile
توی این کلاس هم از فایل خونده میشه ...هم دیکشنری ساخته میشه...
S

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/DataLoading/SerializeJson.cs
> +namespace InvertedIndex{
convert to file scope

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/ClassificationOfArguments.cs
> +namespace InvertedIndex{
file scope

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +        public void Execute(Dictionary<int, List<string>> doc, string[] args)
قبول داری این کلاس وابستس به چندین کلاسی که توشون new شدن؟
و اینطوری داره L توی SOLID نقض میشه؟
چرا هیچ جا از interface ها استفاده نشده؟

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +        public void Execute(Dictionary<int, List<string>> doc, string[] args)
این کلاس داره خیلی کارا میکنه‌ها...حتی چاپ توی خروجی...S

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/MakeIndex/MakeIndex.cs
> +            string[] splitedValue = value.Split(" ");
اگر متن چنین حالتی داشت درست عمی میکنه؟
"                   salam                 hello                hi            "

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/MakeIndex/MakeIndex.cs
> +            string[] splitedValue = value.Split(" ");
خب گیتهاب ننداخت اسپیس های اضفه رو ...منظورم اسپیس اضافه بین کلمات بود

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsAtLeastExist.cs
> +                        continue;
continue 
بود و نبودش فرق داره؟

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsAtLeastExist.cs
> +            }
این تابع خیلی طولانی نیست؟

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustExist.cs
> +        }
طولانی نیست؟
extract method

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustNotExist.cs
> +        }
طولانی...S

2024-09-13 17:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustNotExist.cs
> +    class MustNotExist
same name with file

2024-09-28 13:55 UTC, SeyedMojtaba1 commented on InvertedIndex/Execute/Program.cs
> +            ExecuteSearch exse = new ExecuteSearch();
Ok.

2024-09-28 14:06 UTC, SeyedMojtaba1 commented on InvertedIndex/Execute/Program.cs
> +            }
Instead of that solution I used Skip and Take functions.

2024-09-28 14:06 UTC, SeyedMojtaba1 commented on InvertedIndex/Execute/Program.cs
> +            ReadtxtFile rtf = new ReadtxtFile();
Ok.

2024-09-28 14:18 UTC, SeyedMojtaba1 commented on InvertedIndex/Execute/Program.cs
> +            ReadtxtFile rtf = new ReadtxtFile();
مطالعه کردم درباره ش.

2024-09-30 07:16 UTC, SeyedMojtaba1 commented on InvertedIndex/DataLoading/ReadFiles.cs
> +        public Dictionary<int, List<string>> ExtarcAllFiles(string path)
اصلاح شد.

2024-09-30 07:16 UTC, SeyedMojtaba1 commented on InvertedIndex/DataLoading/ReadFiles.cs
> +            Dictionary<int, List<string>> doc = new Dictionary<int, List<string>>();
Ok.

2024-09-30 07:17 UTC, SeyedMojtaba1 commented on InvertedIndex/DataLoading/ReadFiles.cs
> +    class ReadtxtFile
Ok.

2024-10-01 06:13 UTC, SeyedMojtaba1 commented on InvertedIndex/WordTypeDetection/WordsAtLeastExist.cs
> +                        continue;
نه درواقع. حذفش کردم.

2024-10-01 06:15 UTC, SeyedMojtaba1 commented on InvertedIndex/WordTypeDetection/WordsAtLeastExist.cs
> +            }
به خاطر سرچ روی تمام آرگومان ها این تابع بزرگ شده و ایده دیگه ای در پیاده سازیش به ذهنم نرسید.

2024-10-01 06:20 UTC, SeyedMojtaba1 commented on InvertedIndex/WordTypeDetection/WordsMustExist.cs
> +        }
من از این متد برای شرط‌هام استفاده کردم اما برای foreach ها نه. آیا لازمه؟

2024-10-01 06:21 UTC, SeyedMojtaba1 commented on InvertedIndex/WordTypeDetection/WordsMustNotExist.cs
> +    class MustNotExist
ok.

2024-10-03 20:44 UTC, navidnasyry requested changes

2024-10-03 20:44 UTC, navidnasyry commented on .vscode/settings.json
؟؟؟

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/Execute/Program.cs
> +            doc = readtxtFile.ExtarctAllFiles(args[0]);
چرا دیگه نیو شده؟

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            }
S Solid:)
این کلاس کارش این نیست درسته؟

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            }
پس بهتره چه کنیم؟

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            contain = _wordsMustNotExist.SearchInRemDocs(doc, contain, arguments[2]);
مشخص نیست arg[1] و ۲و ... چین؟
یه سرویسی داشته باشیم که اینا رو بهمون بده چطوره؟

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            var contain = new List<int>();
چرا نیو شده؟

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            contain = _wordsMustNotExist.SearchInRemDocs(doc, contain, arguments[2]);
نمیفهمم...چرا هر بار ورودی میدی و میریزی تو خودش؟
راه بهتر...

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsAtLeastExist.cs
> +        }
public or private?

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustExist.cs
> +    interface IWordsMustExist
filescope

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsAtLeastExist.cs
> +namespace InvertedIndex{
چرا اینترفیس و کلاس تو یه فایلن؟؟؟؟؟؟؟؟
یه پوشه باید باشه به نام Abstraction و یکی Service که توشون اینترفیس ها و سرویس ها یا کلاس ها باشن

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsAtLeastExist.cs
> +            }
extract method

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustExist.cs
> +                }
extract method

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustNotExist.cs
> +            }
e m

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/Execute/ClassificationOfArguments.cs
> +                }
open close?

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/.gitignore
?

2024-10-03 20:44 UTC, navidnasyry commented on InvertedIndex/DataLoading/ReadtxtFiles.cs
> +namespace InvertedIndex{
چرا تو یه فایل؟:(

2025-03-30 21:54 UTC, navidnasyry requested changes

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            _classificationOfArguments = classificationOfArguments;
check null input

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            contain = _wordsMustNotExist.SearchInRemDocs(doc, contain, arguments[2]);
همین کامنت...

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            }
نوشتن توی console کار این کلاسه؟
S SOLID

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/Execute/ExecuteSearch.cs
> +            contain = _wordsMustNotExist.SearchInRemDocs(doc, contain, arguments[2]);
ببین برا این کار میتونی یه دیزاین پترن خوب بیاری...؟

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/Execute/ClassificationOfArguments.cs
> +    internal class ClassificationOfArguments : IClassificationOfArguments
اسم بهتر
معمولا اسم کلاس ها رو به صورت فاعل میذاریم
ArgumentsClassifier
که البته باز هم این اسم کلیه و احتمالا بشه اسم بهتر گذاشت

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/Execute/ClassificationOfArguments.cs
> +                }
is this OpenClose?

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/MakeIndex/MakeIndex.cs
> +            string[] splitedValue = value.Split(" ");
+

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsAtLeastExist.cs
> +    internal class WordsAtLeastExistOne : IWordsAtLeastExistOne
اسم‌های بهتر برای کلاس‌ها

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustExist.cs
> +namespace InvertedIndex
این فایل هم اینترفیس داره هم کلاس؟:(

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustExist.cs
> +        bool CheckEqContainCount(int check, List<string> arg)
مخفف Eq واضح نیست
تا میشه از مخفف ها استفاده نکنیم توی نامگذاری‌ها

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustNotExist.cs
> +        public List<int> SearchInRemDocs(Dictionary<int, List<string>> doc, List<int> contain, List<string> arg)
اسم واضح نیست کارش چیه

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/WordTypeDetection/WordsMustExist.cs
> +
الان با چه order زمانی ای داریم بر میگردونیم نتیجه رو؟
مگه قرار نشد inverted Index پیاده کنیم؟

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/DataLoading/ReadtxtFiles.cs
> +namespace InvertedIndex
توی یه فایل اینترفیس و کلاس؟:((((

2025-03-30 21:54 UTC, navidnasyry commented on InvertedIndex/DataLoading/MakeDictionary.cs
> +namespace InvertedIndex
ایضا

2025-05-02 10:54 UTC, navidnasyry requested changes
درباره DI (Dependency Injection)
بخوان و به پروژه اضافه کن و ازش استفاده کن.

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/ThreeTypesOfIndexDetector/AtLeastOneWordMustExistChecker.cs
> +    internal class AtLeastOneWordMustExistChecker : DocumentSearchHandler
اصل D در  SOLID چه می‌گوید؟

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/ThreeTypesOfIndexDetector/AtLeastOneWordMustExistChecker.cs
> +    internal class AtLeastOneWordMustExistChecker : DocumentSearchHandler
آیا اینجا رعایت شده؟

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/ThreeTypesOfIndexDetector/AtLeastOneWordMustExistChecker.cs
> +    internal class AtLeastOneWordMustExistChecker : DocumentSearchHandler
read about strategy pattern design

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/ThreeTypesOfIndexDetector/AtLeastOneWordMustExistChecker.cs
> +    internal class AtLeastOneWordMustExistChecker : DocumentSearchHandler
read about chain responsiblity

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/Abstraction/DocumentSearchHandler.cs
> +    using Interfaces;
use filescope

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/Abstraction/DocumentSearchHandler.cs
> +    using Interfaces;
ussing is upper than namespaces

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/Abstraction/DocumentSearchHandler.cs
> +    internal abstract class DocumentSearchHandler : IDocumentSearchHandler
توی پوشه abstractions 
اینترفیس‌ ها رو میذاریم

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/Abstraction/DocumentSearchHandler.cs
> +    internal abstract class DocumentSearchHandler : IDocumentSearchHandler
بهتره اصلا کلاس abstract نداشته باشیم. چرا؟

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/FileExtracter/FilesToDictionaryParser.cs
> +            IFileNamesExtracter fileNamesExtracter = new FileNamesExtracter();
اینا رو هم ورودی کانستراکتور بگیریم و مقدار بدیم مثل IDictionaryFromFileMarker

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/FileExtracter/FilesToDictionaryParser.cs
> +            ITextFileReader textFileReader = new TextFileReader();
""

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/services/FileExtracter/FilesToDictionaryParser.cs
> +            IFileNamesExtracter fileNamesExtracter = new FileNamesExtracter();
چرا این بهتره؟

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/Controllers/Executor/InputArgumentsSearcher.cs
> +            var mustNotExistHandler = new WordsMustNotExistChecker(arguments[2]);
اینا چطور تست شدن؟

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex/Controllers/Executor/InputArgumentsSearcher.cs
> +            var mustNotExistHandler = new WordsMustNotExistChecker(arguments[2]);
چرا سخته تست نویسی برا اینا؟

2025-05-02 10:54 UTC, navidnasyry commented on InvertedIndex.Test/ClassificationOfArgumentsTest.cs
> +namespace InvertedIndex.Test
namespace هر کلاس تست
با خود کلاسی که داره تست میشه یکی بشه

به عبارت دیگه فولدربندیشون دقیقا مثل هم باشه

2025-05-09 21:48 UTC, navidnasyry requested changes

2025-05-09 21:48 UTC, navidnasyry commented on InvertedIndex.Test/WordsMustExistTest.cs
> +        public void Test1()
search about test naming conventions

2025-05-09 21:48 UTC, navidnasyry commented on InvertedIndex.Test/WordsMustExistTest.cs
> +        {
// Arrange
// Act
// Assert

2025-05-09 21:48 UTC, navidnasyry commented on InvertedIndex.Test/WordsMustExistTest.cs
> +        {
Read about AAA testing approach

2025-05-09 21:48 UTC, navidnasyry commented on InvertedIndex.Test/WordsMustExistTest.cs
> +        {
برای همه بقیه تست ها هم رعایت شود همه موارد.

2025-05-09 21:48 UTC, navidnasyry commented on InvertedIndex.Test/MakeIndexTest.cs
> +using System.Linq; // Required for SequenceEqual
کامنت چیه؟

2025-09-20 16:56 UTC, merged